# Generated by Django 5.1.4 on 2025-01-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinations',
            name='dest_image',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='Destinations/'),
        ),
    ]
