# Generated by Django 5.1.4 on 2025-01-11 09:03

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_destinations_dest_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinations',
            name='dest_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='destinations',
            name='dest_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='dest_name', unique=True),
        ),
    ]
