# Generated by Django 5.1.4 on 2025-01-24 07:52

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_alter_destinations_dest_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinations',
            name='dest_category',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='destinations',
            name='news_description',
            field=tinymce.models.HTMLField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='destinations',
            name='dest_desc',
            field=models.TextField(default=None, null=True),
        ),
    ]
