# Generated by Django 5.1.4 on 2025-01-25 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0004_destinations_dest_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinations',
            name='lat',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='destinations',
            name='long',
            field=models.FloatField(default=None, null=True),
        ),
    ]
