# Generated by Django 5.1.4 on 2025-01-25 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0005_destinations_lat_destinations_long'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinations',
            name='dest_image1',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='Destinations/'),
        ),
        migrations.AddField(
            model_name='destinations',
            name='dest_image2',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='Destinations/'),
        ),
        migrations.AddField(
            model_name='destinations',
            name='dest_image3',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='Destinations/'),
        ),
        migrations.AddField(
            model_name='destinations',
            name='dest_image4',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='Destinations/'),
        ),
    ]
