# Generated by Django 5.1.4 on 2025-01-29 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0006_destinations_dest_image1_destinations_dest_image2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='emergincy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagory', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('area', models.CharField(max_length=100)),
                ('location', models.URLField()),
            ],
        ),
    ]
